// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBookmark.Data;

namespace OnlineBookmark.Migrations.OnlineBookmarkDb
{
    [DbContext(typeof(OnlineBookmarkDbContext))]
    partial class OnlineBookmarkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineBookmark.Data.Models.Bookmark", b =>
                {
                    b.Property<string>("Bid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BaseBid")
                        .IsRequired();

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("Bid");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("OnlineBookmark.Data.Models.BookmarkBase", b =>
                {
                    b.Property<string>("BaseBid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ImageFilePath");

                    b.Property<string>("LinkedUrl");

                    b.Property<string>("OwnerUid")
                        .IsRequired();

                    b.HasKey("BaseBid");

                    b.ToTable("BookmarkBases");
                });

            modelBuilder.Entity("OnlineBookmark.Data.Models.UserBookmark", b =>
                {
                    b.Property<decimal>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<string>("Bid")
                        .IsRequired();

                    b.Property<bool>("IsPrivate");

                    b.Property<string>("Uid")
                        .IsRequired();

                    b.HasKey("Seq");

                    b.ToTable("UserBookmarks");
                });

            modelBuilder.Entity("OnlineBookmark.Data.Models.UserProfile", b =>
                {
                    b.Property<string>("Uid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(20);

                    b.Property<string>("IconPath")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Uid");

                    b.ToTable("UserProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
